{
 "title": "Travis Build Stats",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Total Builds",
   "type": "singlestat",
   "description": "This is the total number of builds",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "sum(builds_duration_ms_count)" }
   ]
  },
  {
   "title": "percent failed",
   "type": "singlestat",
   "description": "Percent of builds that are failed.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "(sum(builds_duration_ms_count{check_run_conclusion=\"failure\"}) or (1-sum(absent(builds_duration_ms_count{check_run_conclusion=\"failure\"}))))/sum(builds_duration_ms_count)*100"
    }
   ]
  },
  {
   "title": "Probot Uptime",
   "type": "singlestat",
   "description": "Probot Uptime",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "up * 100" }
   ]
  },
  {
   "title": "Build Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ms", "label": "duration" }
   ],
   "targets": [
    {
     "expr": "avg(builds_duration_ms{check_run_conclusion=\"failure\"})",
     "legendFormat": "failed builds"
    },
    {
     "expr": "avg(builds_duration_ms{check_run_conclusion=\"success\"})",
     "legendFormat": "successful builds"
    },
    {
     "expr": "avg(builds_duration_ms_sum/builds_duration_ms_count)",
     "legendFormat": "all builds"
    }
   ]
  },
  {
   "title": "Build Success Percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1-(sum(builds_duration_ms_count{check_run_conclusion=\"failure\"}) or (1-absent(sum(builds_duration_ms_count{check_run_conclusion=\"failure\"}))))/sum(builds_duration_ms_count))*100",
     "legendFormat": "percent success"
    }
   ]
  }
 ]
}